# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      copy_builder:
        generate_for:
          include:
            - test/helper/*

builders:
  copy_builder:
    import: "package:copy_builder/builder.dart"
    builder_factories: ["copyBuilder"]
    build_extensions: {".dart": [".copy.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      options:

