name: copy_builder
description: copy_builder
version: 0.0.1
homepage: https://github.com/kosukesaigusa/copy_builder
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.1.0
  build: ^2.4.1
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.6
  dart_style: ^2.3.3
  test: ^1.23.3
