name: copy_builder
description: copy_builder
version: 0.0.1
homepage: https://github.com/kosukesaigusa/dart_from_json_generator
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.23.3
