name: from_json_generator

repository: https://github.com/kosukesaigusa/from_json_generator

packages:
  - packages/**
  - packages/**/example

sdkPath: .fvm/flutter_sdk

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pg:
    run: melos exec -- "flutter pub get"

  clpg:
    run: melos exec -- "flutter clean && flutter pub get"

  build:
    run: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"

  test:
    run: melos exec -- "flutter test"

  analyze:
    run: melos exec -- "flutter analyze ."

  format:
    run: melos exec -- "dart format ."
