name: from_json_generator_annotation
description: from_json_generator_annotation
version: 0.0.1
homepage: https://github.com/kosukesaigusa/dart_from_json_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1
