# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      from_json_generator:
        generate_for:
          include:
            - test/helper/*

builders:
  from_json_generator:
    import: "package:from_json_generator/builder.dart"
    builder_factories: ["fromJsonGenerator"]
    build_extensions: {".dart": [".from_json.dart"]}
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        field_rename: none
