name: from_json_generator
description: from_json_generator
version: 0.0.1
homepage: https://github.com/kosukesaigusa/dart_from_json_generator
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.1.0
  build: ^2.4.1
  from_json_generator_annotation:
    path: ../from_json_generator_annotation
  json_annotation: ^4.8.1
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
